apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ground-station
spec:
  source:
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'ground-station:latest'
  failedBuildsHistoryLimit: 2
  successfulBuildsHistoryLimit: 2
